config/routes.rb
Rails.application.routes.draw do
  root to: "notes#index"
  get '/notes/:id/finalize', to: "notes#finalize"
  get '/notes/all', to: "notes#ver_todas"
  get '/notes/end', to: "notes#finalizeds"

  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
          http_basic_authenticate_with name: "gerson", password: "gerson"

  def index
		@notes = Note.where("status = 0")
		render 'index'
	end

	def ver_todas
          @notes = Note.order(:status)
          render 'index'
	end

	def finalizeds
          @notes = Note.where("status = 1")
          render 'index'
	end

	def new
		@novo = Note.new
	end

	def create
          @novo = Note.new params.require(:note).permit(:titulo, :texto)
	  @novo.status = 0
          if @novo.save then
            redirect_to root_url
            flash[:notice] = 'Nota criada com sucesso!'
          else
            redirect_to "/produtos/new"
          end
	end

	def show
		@selected = Note.find(params[:id])
	end

	def edit
		@selected = Note.find(params[:id])
	end

	def update
          titulo = params[:note][:titulo]
          texto= params[:note][:texto]
          @selected = Note.find(params[:id])
          @selected.update(titulo: titulo, texto:texto)
          redirect_to note_path(@selected.id)
	end

	def finalize
          @selected = Note.find(params[:id])
          @selected.update(status: 1)
          redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if flash[:notice] %>
      <div class="alert alert-success text-center" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-5 text-center"><h1 style="color:white"> Bem Vindo a sua agenda.</h1></div>
  <div class="col-sm-3"></div>
</div>
<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
<table class="table table-striped">
  <tr><td><%=link_to "Todas", '/notes/all', class: "btn btn-primary"%></td>
  <td><%=link_to "Pendentes", root_path, class: "btn btn-success"%></td>
  <td><%=link_to "Finalizadas", '/notes/end',class: "btn btn-danger" %></td>
  <td><%=link_to "Nova Nota", new_note_path, class: "btn btn-success"%></td>
</tr>  	
</table>
  </div>
  <div class="col-sm-4"></div>
</div>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<html>
<body style="background-color: CornflowerBlue">
<div class="container">
<h1 style="color: MediumTurquoise">Alterando nota:</h1>
<%= form_for @selected, html: { multipart: true } do |f| %>
<div class="form-group" style="color: white">
<%= f.label :titulo %>   
<%= f.text_field :titulo, class: "form-control"%>
</div>

<div class="form-group" style="color: white">
<%= f.label :texto %>  
<%= f.text_area :texto, class: "form-control" %><br><br>
</div>

<%= f.submit "Salvar Nota", class: "btn btn-primary" %>
<%=link_to '   Voltar  ', root_path, class: "btn btn-warning"%>
<% end %>
</div>
</body>
</html>

app/views/notes/index.html.erb
<body style="background-color: CornflowerBlue">
<div class="container">
<div class="container">


<br>
<div class="container" style="margin-top: 20px">
<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">  
  <table class="table table-bordered">
      <tr>
      <th scope="col"><h3 style="color:white" >Lista de notas:</h3></th>
    </tr>
  </thead>
  <% @notes.each do |note|%>
  <%if note.status.chomp.to_i==0 %>
  <tr><td><p><%= link_to note.titulo, note_path(note.id), class: "btn btn-success"%></p></td></tr>
  <%else%>
  <tr><td><p><%= link_to note.titulo, note_path(note.id), class: "btn btn-danger"%></p></td></tr>
<%end end%>
</table></div>
  <div class="col-sm-4"></div>
</div>
</div>
</div>


app/views/notes/new.html.erb
<html>
<body style="background-color: CornflowerBlue">
<div class="container">
<h1 style="color: MediumTurquoise">Nova nota:</h1>
<%= form_for Note.new, html: { multipart: true } do |f| %>
<div class="form-group" style="color: white">
<%= f.label :titulo %>   
<%= f.text_field :titulo, class: "form-control"%>
</div>

<div class="form-group" style="color: white">
<%= f.label :texto %>  
<%= f.text_area :texto, class: "form-control" %><br><br>
</div>

<%= f.submit "Salvar Nota", class: "btn btn-primary" %>
<%=link_to '   Voltar  ', root_path, class: "btn btn-warning"%>
<% end %>
</div>
</body>
</html>

app/views/notes/show.html.erb
<body style="background-color: CornflowerBlue">
<div class="container">
<div class="container" style="margin-top: 20px">
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">  
  <table class="table table-bordered">
      <tr>
      <th scope="col"><h1 style="color:white"><%=@selected.titulo%></h1></th>
    </tr>
  </thead>
  <tr><td><p style="color:white"><%=@selected.texto%></p></td></tr>
  <%if @selected.status.chomp.to_i==1%>
  <tr><td><p style="color:red">*Esta tarefa já foi finalizada.</p></td></tr>
  <%end%>
</table></div>
  <div class="col-sm-3"></div>
</div>
</div>
</div>
</div>




<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
<table class="table">
  <tr><td><%=link_to '   Editar   ', edit_note_path(@selected.id), class: "btn btn-primary"%></td>
  <td><%=link_to 'Finalizar tarefa', "/notes/#{@selected.id}/finalize", class: "btn btn-primary" %></td>
  <td><%=link_to '   Voltar  ', root_path, class: "btn btn-warning"%></td>
</tr>  	
</table>
  </div>
  <div class="col-sm-4"></div>
</div>
</body>


